services:
  musegan:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    ports:
      - "5000:5000"
    volumes:
      - /dev/shm:/dev/shm
      - ./outputs:/app/musegan/v1/exps/temporal_hybrid/output/custom_generate
      - ./exps:/app/musegan/v1/exps
