version: '3.8'

services:
  musicgen:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
      - ./lmd_full:/app/lmd_full
      - ~/.cache:/root/.cache
    working_dir: /app
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
